export enum ENNaming {
    userAll = 'userAll',
    DYNAMICID = 'dynamicId',
    userLineGetByUserId = 'userLineGetByUserId',
    userLineGetByLineId = 'userLineGetByLineId',
    role = 'role',
    provider = 'provider',
    templateCategory = 'templateCategory',
    template = 'template',
    configTypeGroup = 'configTypeGroup',
    ccSend = 'ccSend',
    permittedTime = 'permittedTime',
    disallowedPhrase = 'disallowedPhrase',
    line = 'line',
    choose = 'انتخاب کنید',
    tableEmptyMessage = 'موردی یافت نشد',
    currentPageReportText = 'Showing {first} to {last} of {totalRecords} entries',
    successRemove = 'حذف با موفقیت انجام شد',
    successEdit = 'ویرایش با موفقیت انجام شد',
    successCreate = 'افزودن با موفقیت انجام شد',
    deleteConfirmMessage= 'شما درحال حذف این مورد هستید، اطمینان دارید؟'
}    