export enum ENNaming {
    userAll = 'userAll',
    userCreate = 'userCreate',
    DYNAMICID = 'dynamicId',
    userLineGetByUserId = 'userLineGetByUserId',
    userLineGetByLineId = 'userLineGetByLineId',
    role = 'role',
    provider = 'provider',
    templateCategory = 'templateCategory',
    template = 'template',
    configTypeGroup = 'configTypeGroup',
    ccSend = 'ccSend',
    permittedTime = 'permittedTime',
    disallowedPhrase = 'disallowedPhrase',
    line = 'line',
    choose = 'انتخاب کنید',
    tableEmptyMessage = 'اطلاعاتی برای نمایش وجود ندارد',
    paginatorTemplate = 'FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown',
    currentPageReportText = 'نمایش از {first} تا {last} از {totalRecords} مورد',
    successRemove = 'حذف با موفقیت انجام شد',
    successEdit = 'ویرایش با موفقیت انجام شد',
    successCreate = 'افزودن با موفقیت انجام شد',
    deleteConfirmMessage = 'شما درحال حذف این مورد هستید، اطمینان دارید؟'
}    